=== How to use JMeter to load test your Neo4j custom procedures / queries

When working with https://neo4j.com/[Neo4j], sometimes you need to create custom procedures to handle
use cases like advanced permissions, custom traversals, or high performance data import.

https://jmeter.apache.org/[JMeter] is a popular tool for load testing, and can be used
to build complex testing scenarios, with custom ramp up periods, sample data
as CSV file, ...

This repository contains help on how to configure and use JMeter to run Neo4j queries
through the https://boltprotocol.org/[Bolt protocol].

An introduction video to load testing a procedure with JMeter can be found here:
https://youtu.be/Zqyeo0iShF4

It uses a custom version of JMeter that handles the bolt protocol.
This custom version can be found at https://github.com/graphaware/jmeter/.
Check out the build instructions located in the `README-bolt.md`.

We are working with the JMeter team to integrate bolt into
the main JMeter codebase, so hopefully,

These examples have been created at the occasion of the
https://globalgraphhack.devpost.com/[2019 Global GraphHack]

